/**
 * Classical Astrometeorological Lunar Mansions (Anwa' al-Manazil - علم الأنواء)
 * Based on Kitab al-Anwa' (Ibn Qutaybah), Risalah fi al-Anwa' (Al-Kindi),
 * and Zij as-Sindhind classical meteorological rules.
 */

export interface ManzilWeatherProfile {
  number: number;
  arabicName: string;
  transliteration: string;
  starGroup: string;
  zodiacSpan: string;
  startDegree: number;
  endDegree: number;
  seasonKey: 'spring' | 'summer' | 'autumn' | 'winter';
  seasonName: string;
  seasonArabic: string;
  element: 'Nar' | 'Turab' | 'Hawa' | 'Ma'; // Api, Tanah, Udara, Air
  elementLabel: string;
  // Historical Rainfall & Precipitation index (0 = Sangat Gersang / Qahat, 100 = Banjir Bandang / Ghazir)
  rainfallProbability: number;
  rainfallVolumeMm: number; // Historical relative volume index
  rainfallClassification: 'Ghazir' | 'Wasmi' | 'Ghayth' | 'Tal' | 'Jaff';
  rainfallLabel: string;
  rainfallArabic: string;
  // Temperature index (0 = Dingin Beku / Jalid, 100 = Puncak Terik Samum)
  temperatureIndex: number;
  temperatureLabel: string;
  temperatureArabic: string;
  // Wind characteristics
  windDirection: 'Timur (as-Saba)' | 'Barat (ad-Dabur)' | 'Selatan (al-Janub)' | 'Utara (ash-Shamal)';
  windArabic: string;
  windCharacteristics: string;
  // Moisture Gate (Fath al-Bab) - special astrological gate of atmospheric moisture
  isMoistureGate: boolean;
  gateDescription: string;
  // Agricultural and navigation advice
  agriculturalIndication: string;
  nauticalIndication: string;
  // Classical poetry verse from Kitab al-Anwa'
  poeticVerse: string;
  poeticVerseTranslation: string;
}

export const MANZIL_WEATHER_PROFILES: ManzilWeatherProfile[] = [
  {
    number: 1,
    arabicName: 'الشَّرَطَان',
    transliteration: 'Ash-Sharatan',
    starGroup: 'β & γ Arietis (Tanduk Domba)',
    zodiacSpan: '0°00\' - 12°51\' Aries (Al-Ḥamal)',
    startDegree: 0,
    endDegree: 12.8571,
    seasonKey: 'spring',
    seasonName: 'Musim Semi (Ar-Rabī‘)',
    seasonArabic: 'الرَّبِيع',
    element: 'Nar',
    elementLabel: 'Api (Ḥārr Yābis)',
    rainfallProbability: 45,
    rainfallVolumeMm: 35,
    rainfallClassification: 'Tal',
    rainfallLabel: 'Gerimis Awal Semi (Ṭall)',
    rainfallArabic: 'طَلٌّ وَرَذَاذٌ رَبِيعِيّ',
    temperatureIndex: 52,
    temperatureLabel: 'Sejuk Menghangat',
    temperatureArabic: 'مُعْتَدِلٌ مَائِلٌ لِلدِّفْء',
    windDirection: 'Timur (as-Saba)',
    windArabic: 'رِيَاحُ الصَّبَا الرَّطْبَة',
    windCharacteristics: 'Angin timur sejuk pembawa aroma bunga dan kelembaban awal.',
    isMoistureGate: true,
    gateDescription: 'Gerbang awal terbukanya siklus vegetasi bumi dan pencairan sisa embun beku.',
    agriculturalIndication: 'Waktu utama membajak tanah ladang, menebar benih gandum musim semi, dan mencangkok tanaman.',
    nauticalIndication: 'Aman untuk pelayaran pesisir, ombak laut mulai mereda dari badai musim dingin.',
    poeticVerse: 'إِذَا طَلَعَ الشَّرَطَانِ اعْتَدَلَ الزَّمَان، وَتَهَادَتِ السِّمَان، وَحَضَرَتِ الرِّعْيَان',
    poeticVerseTranslation: 'Bila Sharatan terbit fajar, berangsur seimbanglah cuaca zaman, hewan gembala menggemuk dan pengembala bersuka cita.',
  },
  {
    number: 2,
    arabicName: 'البُطَيْن',
    transliteration: 'Al-Butayn',
    starGroup: 'δ, ε, ρ Arietis (Perut Domba)',
    zodiacSpan: '12°51\' - 25°43\' Aries (Al-Ḥamal)',
    startDegree: 12.8571,
    endDegree: 25.7143,
    seasonKey: 'spring',
    seasonName: 'Musim Semi (Ar-Rabī‘)',
    seasonArabic: 'الرَّبِيع',
    element: 'Turab',
    elementLabel: 'Tanah (Bārid Yābis)',
    rainfallProbability: 38,
    rainfallVolumeMm: 25,
    rainfallClassification: 'Tal',
    rainfallLabel: 'Hujan Sporadis Ringan',
    rainfallArabic: 'مَطَرٌ خَفِيفٌ مُتَفَرِّق',
    temperatureIndex: 58,
    temperatureLabel: 'Hangat Nyaman',
    temperatureArabic: 'دَفِيءٌ صَافِي الجَوّ',
    windDirection: 'Utara (ash-Shamal)',
    windArabic: 'شَمَالِيَّةٌ هَادِئَة',
    windCharacteristics: 'Angin utara sepoi yang mengeringkan lumpur dan menstabilkan cuaca.',
    isMoistureGate: false,
    gateDescription: 'Pintu kelembaban tertutup sementara; langit cenderung cerah tak berawan.',
    agriculturalIndication: 'Penyiangan gulma dan pemangkasan dahan pohon buah yang mulai berkuncup.',
    nauticalIndication: 'Kondisi laut tenang dengan jarak pandang sangat baik.',
    poeticVerse: 'إِذَا طَلَعَ البُطَيْن اقْتُفِيَ اللَّيْن، وَزَالَ الضَّيْن، وَظَهَرَ زَيْنُ النَّبَات',
    poeticVerseTranslation: 'Kala Butayn tampak, kelembutan udara diikuti, kesukaran lenyap dan perhiasan tumbuhan bersemi.',
  },
  {
    number: 3,
    arabicName: 'الثُّرَيَّا',
    transliteration: 'Ath-Thurayya',
    starGroup: 'Pleiades (Gugus Tujuh Bintang)',
    zodiacSpan: '25°43\' Aries - 8°34\' Taurus (Ath-Thawr)',
    startDegree: 25.7143,
    endDegree: 38.5714,
    seasonKey: 'spring',
    seasonName: 'Musim Semi (Ar-Rabī‘)',
    seasonArabic: 'الرَّبِيع',
    element: 'Hawa',
    elementLabel: 'Udara (Ḥārr Raṭb)',
    rainfallProbability: 88,
    rainfallVolumeMm: 85,
    rainfallClassification: 'Ghazir',
    rainfallLabel: 'Hujan Berkah Lebat (Naw\' al-Ghayth)',
    rainfallArabic: 'أَبَرُّ الأَنْوَاءِ مَطَرًا وَغَيْثًا',
    temperatureIndex: 64,
    temperatureLabel: 'Hangat Tropis Lembab',
    temperatureArabic: 'حَارٌّ رَطْبٌ كَثِيرُ البَرَكَة',
    windDirection: 'Timur (as-Saba)',
    windArabic: 'صَبَا جَالِبَةٌ لِلسَّحَاب',
    windCharacteristics: 'Angin pembawa awan tebal bermuatan air deras dan kilat berkah.',
    isMoistureGate: true,
    gateDescription: 'Gerbang air utama! Naw\' paling masyhur dalam tradisi astronomi Arab sebagai pembawa hujan penyubur bumi.',
    agriculturalIndication: 'Masa penanaman terpenting! Air hujan Thurayya diyakini membersihkan penyakit tanaman (*Al-‘Āhah*).',
    nauticalIndication: 'Waspada badai kilat mendadak di laut lepas.',
    poeticVerse: 'إِذَا طَلَعَتِ الثُّرَيَّا مَطَرَتْ كُلَّ عَيْهَلَة، وَرُوِيَتِ الهِضَابُ وَالأَوْدِيَة',
    poeticVerseTranslation: 'Jika Thurayya menumpahkan hujannya, tanah tandus pun basah kuyup, bukit dan lembah tergenang air melimpah.',
  },
  {
    number: 4,
    arabicName: 'الدَّبَرَان',
    transliteration: 'Ad-Dabaran',
    starGroup: 'α Tauri (Aldebaran)',
    zodiacSpan: '8°34\' - 21°26\' Taurus (Ath-Thawr)',
    startDegree: 38.5714,
    endDegree: 51.4286,
    seasonKey: 'spring',
    seasonName: 'Musim Semi (Ar-Rabī‘)',
    seasonArabic: 'الرَّبِيع',
    element: 'Nar',
    elementLabel: 'Api (Ḥārr Yābis)',
    rainfallProbability: 18,
    rainfallVolumeMm: 12,
    rainfallClassification: 'Jaff',
    rainfallLabel: 'Gersang & Terik (Majdah)',
    rainfallArabic: 'قَحْطٌ وَجَفَافٌ مَجْدَحِيّ',
    temperatureIndex: 72,
    temperatureLabel: 'Mulai Terik Menyengat',
    temperatureArabic: 'حَرٌّ قَائِظٌ مُبَكِّر',
    windDirection: 'Selatan (al-Janub)',
    windArabic: 'سَمُومٌ جَنُوبِيَّةٌ حَارَّة',
    windCharacteristics: 'Hembusan angin panas yang mengeringkan genangan air dan meniupkan debu halus.',
    isMoistureGate: false,
    gateDescription: 'Pintu air tertutup rapat; bintang merah ini secara historis dikenal berwatak kering tajam.',
    agriculturalIndication: 'Pengairan intensif diperlukan. Waspada kekeringan pada tanaman muda.',
    nauticalIndication: 'Laut tenang tetapi udara di atas kapal sangat menyengat dan menguras dahaga.',
    poeticVerse: 'إِذَا طَلَعَ الدَّبَرَان تَوَقَّدَتِ الحِزَان، وَيَبِسَ الغُدْرَان، وَنَشَفَ الرِّيقُ فِي اللِّسَان',
    poeticVerseTranslation: 'Bila Dabaran terbit, tanah berbatu membara panas, telaga mengering dan air liur mengering di lidah.',
  },
  {
    number: 5,
    arabicName: 'الهَقْعَة',
    transliteration: 'Al-Haq‘ah',
    starGroup: 'λ, φ1, φ2 Orionis (Kepala Orion)',
    zodiacSpan: '21°26\' Taurus - 4°17\' Gemini (Al-Jawzā’)',
    startDegree: 51.4286,
    endDegree: 64.2857,
    seasonKey: 'spring',
    seasonName: 'Musim Semi (Ar-Rabī‘)',
    seasonArabic: 'الرَّبِيع',
    element: 'Hawa',
    elementLabel: 'Udara (Ḥārr Raṭb)',
    rainfallProbability: 35,
    rainfallVolumeMm: 22,
    rainfallClassification: 'Tal',
    rainfallLabel: 'Gerimis Hawa Panas',
    rainfallArabic: 'رَذَاذٌ مَعَ دِفْء',
    temperatureIndex: 75,
    temperatureLabel: 'Gerah & Berawan',
    temperatureArabic: 'حَرَارَةٌ رَطْبَةٌ غَائِمَة',
    windDirection: 'Barat (ad-Dabur)',
    windArabic: 'دَبُورٌ دَافِئَة',
    windCharacteristics: 'Awan kumulus putih tinggi bergumpal di cakrawala petang.',
    isMoistureGate: false,
    gateDescription: 'Pembentukan uap air konvektif lokal tanpa hujan berdurasi panjang.',
    agriculturalIndication: 'Pemetikan buah-buahan awal dan pematangan biji-bijian.',
    nauticalIndication: 'Kondisi navigasi baik, angin bertiup stabil dari arah barat.',
    poeticVerse: 'إِذَا طَلَعَتِ الهَقْعَة تَقَوَّضَ النَّاسُ لِلنُّجْعَة، وَطَابَتِ القَيْلُولَةُ فِي البُقْعَة',
    poeticVerseTranslation: 'Ketika Haq‘ah terbit, manusia berpindah mencari naungan teduh, dan nikmatlah tidur siang di bilik dingin.',
  },
  {
    number: 6,
    arabicName: 'الهَنْعَة',
    transliteration: 'Al-Han‘ah',
    starGroup: 'γ & ξ Geminorum',
    zodiacSpan: '4°17\' - 17°09\' Gemini (Al-Jawzā’)',
    startDegree: 64.2857,
    endDegree: 77.1429,
    seasonKey: 'spring',
    seasonName: 'Musim Semi (Ar-Rabī‘)',
    seasonArabic: 'الرَّبِيع',
    element: 'Ma',
    elementLabel: 'Air (Bārid Raṭb)',
    rainfallProbability: 60,
    rainfallVolumeMm: 50,
    rainfallClassification: 'Wasmi',
    rainfallLabel: 'Hujan Petir Musim Semi Akhir',
    rainfallArabic: 'أَمْطَارٌ رَعْدِيَّةٌ مُنْعِشَة',
    temperatureIndex: 70,
    temperatureLabel: 'Hangat Sejuk Seimbang',
    temperatureArabic: 'مُعْتَدِلُ الحَرَارَة',
    windDirection: 'Timur (as-Saba)',
    windArabic: 'صَبَا سَرِيعَة',
    windCharacteristics: 'Angin kencang sesaat sebelum hujan petir membersihkan udara.',
    isMoistureGate: true,
    gateDescription: 'Pintu air konvektif: pertemuan massa udara panas dengan kelembaban laut.',
    agriculturalIndication: 'Sangat baik untuk pertumbuhan sayur-mayur dan buah semangka serta melon.',
    nauticalIndication: 'Waspada gusting wind (angin ribut lokal singkat) di sore hari.',
    poeticVerse: 'إِذَا طَلَعَتِ الهَنْعَة أَنْزَلَ اللهُ النَّفْعَة، وَشَبِعَتِ الرِّعَاعُ بِالرَّتْعَة',
    poeticVerseTranslation: 'Bila Han‘ah terbit, Allah menurunkan manfaat hujan, dan ternak gembala kenyang memamah rumput segar.',
  },
  {
    number: 7,
    arabicName: 'الذِّرَاع',
    transliteration: 'Adh-Dhira‘',
    starGroup: 'α & β Geminorum (Castor & Pollux)',
    zodiacSpan: '17°09\' Gemini - 0°00\' Cancer (As-Saraṭān)',
    startDegree: 77.1429,
    endDegree: 90.0,
    seasonKey: 'spring',
    seasonName: 'Musim Semi (Ar-Rabī‘)',
    seasonArabic: 'الرَّبِيع',
    element: 'Hawa',
    elementLabel: 'Udara (Ḥārr Raṭb)',
    rainfallProbability: 75,
    rainfallVolumeMm: 68,
    rainfallClassification: 'Ghazir',
    rainfallLabel: 'Hujan Lebat Penutup Musim Semi',
    rainfallArabic: 'غَيْثٌ سَحَّاحٌ مَحْمُود',
    temperatureIndex: 74,
    temperatureLabel: 'Menjelang Musim Panas',
    temperatureArabic: 'حَرَارَةٌ مُتَصَاعِدَةٌ مَعَ مَطَر',
    windDirection: 'Selatan (al-Janub)',
    windArabic: 'جَنُوبٌ مَاطِرَة',
    windCharacteristics: 'Awan nimbostratus luas merata menutupi langit selama 2-3 hari berturut-turut.',
    isMoistureGate: true,
    gateDescription: 'Gerbang pembatas musim semi dan panas; hujan terakhir sebelum kemarau gurun.',
    agriculturalIndication: 'Masa panen raya gandum musim dingin dan penyimpanan hasil bumi ke lumbung.',
    nauticalIndication: 'Arus laut mulai beralih pola musiman monsun.',
    poeticVerse: 'إِذَا طَلَعَ الذِّرَاع كَثُرَ فِي الأَرْضِ الإِمْرَاع، وَامْتَلَأَتِ الأَصْوَاع، وَهَنِئَ الزُّرَّاع',
    poeticVerseTranslation: 'Tatkala Dhira‘ terbit, subur makmurlah bumi, takaran gandum penuh meluap dan petani bersukaria.',
  },
  {
    number: 8,
    arabicName: 'النَّثْرَة',
    transliteration: 'An-Nathrah',
    starGroup: 'Praesepe / M44 (Sarang Lebah Cancer)',
    zodiacSpan: '0°00\' - 12°51\' Cancer (As-Saraṭān)',
    startDegree: 90.0,
    endDegree: 102.8571,
    seasonKey: 'summer',
    seasonName: 'Musim Panas (Aṣ-Ṣayf)',
    seasonArabic: 'الصَّيْف',
    element: 'Ma',
    elementLabel: 'Air (Bārid Raṭb)',
    rainfallProbability: 55,
    rainfallVolumeMm: 40,
    rainfallClassification: 'Wasmi',
    rainfallLabel: 'Kabut Pagi & Gerimis Pesisir',
    rainfallArabic: 'ضَبَابٌ وَرَذَاذٌ سَاحِلِيّ',
    temperatureIndex: 82,
    temperatureLabel: 'Panas Lembab Pesisir',
    temperatureArabic: 'حَرٌّ رَطْبٌ شَدِيدُ النَّدَى',
    windDirection: 'Barat (ad-Dabur)',
    windArabic: 'دَبُورٌ رَطْبَةٌ بَحْرِيَّة',
    windCharacteristics: 'Udara pesisir pekat berkabut embun tebal di waktu fajar.',
    isMoistureGate: true,
    gateDescription: 'Gerbang air musim panas (Inqilab ash-Sayfi); kelembaban laut mencapai puncaknya.',
    agriculturalIndication: 'Pengembangan tanaman kurma dan buah ara (tin); kelembaban memacu kematangan buah.',
    nauticalIndication: 'Jarak pandang pagi terbatas oleh kabut laut pekat (*Dabab*).',
    poeticVerse: 'إِذَا طَلَعَتِ النَّثْرَة قَنِعَتِ العَيْنُ بِالنَّظْرَة، وَأَيْنَعَتِ البُسْرَة، وَطَابَتِ الثَّمَرَة',
    poeticVerseTranslation: 'Kala Nathrah tampak, sejuklah pandangan mata, kurma muda menguning merekah dan buah-buahan lezat dinikmati.',
  },
  {
    number: 9,
    arabicName: 'الطَّرْف',
    transliteration: 'At-Tarf',
    starGroup: 'λ & κ Cancri (Mata Singa)',
    zodiacSpan: '12°51\' - 25°43\' Cancer (As-Saraṭān)',
    startDegree: 102.8571,
    endDegree: 115.7143,
    seasonKey: 'summer',
    seasonName: 'Musim Panas (Aṣ-Ṣayf)',
    seasonArabic: 'الصَّيْف',
    element: 'Nar',
    elementLabel: 'Api (Ḥārr Yābis)',
    rainfallProbability: 15,
    rainfallVolumeMm: 8,
    rainfallClassification: 'Jaff',
    rainfallLabel: 'Kering Menyengat',
    rainfallArabic: 'جَفَافٌ وَحَرٌّ لَافِح',
    temperatureIndex: 88,
    temperatureLabel: 'Sangat Terik',
    temperatureArabic: 'شَدِيدُ الحَرَارَة',
    windDirection: 'Selatan (al-Janub)',
    windArabic: 'سَمُومٌ جَنُوبِيَّة',
    windCharacteristics: 'Angin panas gurun membakar dedaunan hijau bila tidak disiram.',
    isMoistureGate: false,
    gateDescription: 'Pintu air terkunci rapat oleh dominasi unsur api.',
    agriculturalIndication: 'Perlindungan tanaman dari sengatan matahari siang langsung (*Harr al-Qayz*).',
    nauticalIndication: 'Pelayaran terhambat oleh tiupan angin kencang berdebu dari daratan.',
    poeticVerse: 'إِذَا طَلَعَ الطَّرْف بَكَرَ الخَرِيف، وَاحْتِيجَ إِلَى الظِّلِّ اللَّطِيف',
    poeticVerseTranslation: 'Bila Tarf terbit, bayangan musim gugur mulai diintai, dan manusia berlindung di bawah naungan sejuk.',
  },
  {
    number: 10,
    arabicName: 'الجَبْهَة',
    transliteration: 'Al-Jabhah',
    starGroup: 'α (Regulus), γ, ζ, η Leonis',
    zodiacSpan: '25°43\' Cancer - 8°34\' Leo (Al-Asad)',
    startDegree: 115.7143,
    endDegree: 128.5714,
    seasonKey: 'summer',
    seasonName: 'Musim Panas (Aṣ-Ṣayf)',
    seasonArabic: 'الصَّيْف',
    element: 'Nar',
    elementLabel: 'Api (Ḥārr Yābis)',
    rainfallProbability: 10,
    rainfallVolumeMm: 5,
    rainfallClassification: 'Jaff',
    rainfallLabel: 'Puncak Kemarau Terik (Qayz)',
    rainfallArabic: 'قِمَّةُ القَيْظِ وَالجَفَاف',
    temperatureIndex: 94,
    temperatureLabel: 'Puncak Panas Gurun',
    temperatureArabic: 'حَرٌّ قَائِظٌ مُشْتَدّ',
    windDirection: 'Timur (as-Saba)',
    windArabic: 'صَبَا حَارَّةٌ جَافَّة',
    windCharacteristics: 'Udara diam membara di tengah hari; fatamorgana gurun terpapar luas.',
    isMoistureGate: false,
    gateDescription: 'Puncak kekeringan tengah musim panas. Curah hujan hampir nihil.',
    agriculturalIndication: 'Pemetikan kurma kering dan pengeringan kismis serta rempah-rempah.',
    nauticalIndication: 'Angin mati (calm doldrums) di tengah laut, membutuhkan kesabaran berlayar.',
    poeticVerse: 'إِذَا طَلَعَتِ الجَبْهَة مَدَّ اللَّيْلُ نَفَسَه، وَتَمَايَلَتِ النَّخْلَةُ بِخَرَفِهَا',
    poeticVerseTranslation: 'Bila Jabhah terbit, malam mulai memanjangkan nafasnya, dan pohon kurma bergoyang sarat dengan buah matang.',
  },
  {
    number: 11,
    arabicName: 'الزُّبْرَة',
    transliteration: 'Az-Zubrah',
    starGroup: 'δ & θ Leonis (Pundak Singa)',
    zodiacSpan: '8°34\' - 21°26\' Leo (Al-Asad)',
    startDegree: 128.5714,
    endDegree: 141.4286,
    seasonKey: 'summer',
    seasonName: 'Musim Panas (Aṣ-Ṣayf)',
    seasonArabic: 'الصَّيْف',
    element: 'Nar',
    elementLabel: 'Api (Ḥārr Yābis)',
    rainfallProbability: 12,
    rainfallVolumeMm: 6,
    rainfallClassification: 'Jaff',
    rainfallLabel: 'Panas Kering Berangin',
    rainfallArabic: 'هَبَوَاتٌ حَارَّة',
    temperatureIndex: 90,
    temperatureLabel: 'Sangat Panas Menurun Perlahan',
    temperatureArabic: 'قَيْظٌ يَبْدَأُ فِي الانْكِسَار',
    windDirection: 'Utara (ash-Shamal)',
    windArabic: 'شَمَالِيَّةٌ نَاشِفَة',
    windCharacteristics: 'Angin utara kering yang mulai memecah kekakuan hawa panas malam hari.',
    isMoistureGate: false,
    gateDescription: 'Masa transisi pematangan tanah; curah hujan minimal.',
    agriculturalIndication: 'Pembersihan ladang dari sisa jerami dan persiapan pemupukan tanah.',
    nauticalIndication: 'Angin stabil kembali bertiup, navigasi kapal layar membaik.',
    poeticVerse: 'إِذَا طَلَعَتِ الزُّبْرَة بَرَدَتِ الغُدْرَة، وَتَكَسَّرَتِ الحَرَّة، وَاشْتَهَى المَاءَ السَّفْرَة',
    poeticVerseTranslation: 'Bila Zubrah terbit, waktu fajar mulai mendingin, sengatan terik pecah dan musafir bernikmat dengan air segar.',
  },
  {
    number: 12,
    arabicName: 'الصَّرْفَة',
    transliteration: 'As-Sarfah',
    starGroup: 'β Leonis (Denebola / Ekor Singa)',
    zodiacSpan: '21°26\' Leo - 4°17\' Virgo (As-Sunbulah)',
    startDegree: 141.4286,
    endDegree: 154.2857,
    seasonKey: 'summer',
    seasonName: 'Musim Panas (Aṣ-Ṣayf)',
    seasonArabic: 'الصَّيْف',
    element: 'Turab',
    elementLabel: 'Tanah (Bārid Yābis)',
    rainfallProbability: 25,
    rainfallVolumeMm: 15,
    rainfallClassification: 'Tal',
    rainfallLabel: 'Perpalingan Panas Menuju Sejuk (Inṣirāf)',
    rainfallArabic: 'انْصِرَافُ الحَرِّ وَبَدْءُ الاعتدال',
    temperatureIndex: 78,
    temperatureLabel: 'Hangat Sejuk Malam Hari',
    temperatureArabic: 'مُعْتَدِلُ اللَّيْلِ دَافِئُ النَّهَار',
    windDirection: 'Barat (ad-Dabur)',
    windArabic: 'دَبُورٌ مُلَطِّفَة',
    windCharacteristics: 'Angin sepoi penyejuk yang membalikkan arah cuaca ekstrim musim panas.',
    isMoistureGate: true,
    gateDescription: 'Dinamakan As-Sarfah karena "memalingkan" (tashrif) panas menuju sejuknya musim gugur.',
    agriculturalIndication: 'Masa transisi agrikultur; penanaman tanaman musim gugur seperti lobak dan bawang.',
    nauticalIndication: 'Kondisi laut sangat bersahabat untuk perdagangan maritim lintas samudra.',
    poeticVerse: 'إِذَا طَلَعَتِ الصَّرْفَة احْتَاجَ الكِسَاءَ مَنْ كَانَ فِي صُرْفَة، وَانْصَرَفَتِ اللَّوَافِح',
    poeticVerseTranslation: 'Bila Sarfah terbit, orang membutuhkan selimut di serambi, dan hawa panas membakar beringsut pamit.',
  },
  {
    number: 13,
    arabicName: 'العَوَّاء',
    transliteration: 'Al-‘Awwa’',
    starGroup: 'β, η, γ, δ, ε Virginis',
    zodiacSpan: '4°17\' - 17°09\' Virgo (As-Sunbulah)',
    startDegree: 154.2857,
    endDegree: 167.1429,
    seasonKey: 'summer',
    seasonName: 'Musim Panas (Aṣ-Ṣayf)',
    seasonArabic: 'الصَّيْف',
    element: 'Turab',
    elementLabel: 'Tanah (Bārid Yābis)',
    rainfallProbability: 40,
    rainfallVolumeMm: 28,
    rainfallClassification: 'Wasmi',
    rainfallLabel: 'Awal Tanda Musim Hujan (Al-Wasmī)',
    rainfallArabic: 'طَلائِعُ الوَسْمِيِّ الخَرِيفِيّ',
    temperatureIndex: 72,
    temperatureLabel: 'Sejuk Nyaman',
    temperatureArabic: 'طَيِّبُ الهَوَاءِ لَطِيف',
    windDirection: 'Utara (ash-Shamal)',
    windArabic: 'شَمَالٌ بَارِدَةٌ رَطْبَة',
    windCharacteristics: 'Malam hari bertambah dingin, anjing melolong menyambut sejuknya angin utara.',
    isMoistureGate: true,
    gateDescription: 'Pintu gerbang penanda pertama datangnya siklus hujan musim gugur (*Al-Wasmi*).',
    agriculturalIndication: 'Pembersihan saluran irigasi menjelang datangnya musim hujan lebat.',
    nauticalIndication: 'Angin stabil, pelayaran antar pulau lancar dan aman.',
    poeticVerse: 'إِذَا طَلَعَتِ العَوَّاء ضُرِبَ الخِبَاء، وَطَابَ المَاء، وَاشْتَهَى الكِسَاءَ الأُمَرَاء',
    poeticVerseTranslation: 'Bila ‘Awwa’ tampak, tenda perkemahan ditegakkan, air terasa segar dan para bangsawan merindukan mantel hangat.',
  },
  {
    number: 14,
    arabicName: 'السِّمَاك',
    transliteration: 'As-Simak',
    starGroup: 'α Virginis (Spica / Simak al-A‘zal)',
    zodiacSpan: '17°09\' Virgo - 0°00\' Libra (Al-Mīzān)',
    startDegree: 167.1429,
    endDegree: 180.0,
    seasonKey: 'summer',
    seasonName: 'Musim Panas (Aṣ-Ṣayf)',
    seasonArabic: 'الصَّيْف',
    element: 'Hawa',
    elementLabel: 'Udara (Ḥārr Raṭb)',
    rainfallProbability: 72,
    rainfallVolumeMm: 65,
    rainfallClassification: 'Ghazir',
    rainfallLabel: 'Hujan Pembasuh Debu (Naw\' as-Simāk)',
    rainfallArabic: 'نَوْءٌ مَحْمُودٌ سَحَّاحُ الأَمْطَار',
    temperatureIndex: 65,
    temperatureLabel: 'Sejuk Menyejukkan',
    temperatureArabic: 'مُعْتَدِلٌ يَشُوبُهُ بَرْد',
    windDirection: 'Timur (as-Saba)',
    windArabic: 'صَبَا خَرِيفِيَّةٌ مَاطِرَة',
    windCharacteristics: 'Awan hitam tebal menyiram tanah, membersihkan dedaunan pohon zaitun.',
    isMoistureGate: true,
    gateDescription: 'Bintang penabur benih! Curah hujan lebat yang meresap ke dalam cadangan air tanah.',
    agriculturalIndication: 'Waktu terbaik menabur benih gandum musim dingin dan jelai (*Ash-Sha‘īr*).',
    nauticalIndication: 'Waspada ombak pasang tinggi akibat perubahan tekanan udara musim gugur.',
    poeticVerse: 'إِذَا طَلَعَ السِّمَاك جَاءَكَ المَاءُ يَنْسَاك، وَامْتَلَأَتِ الحِيَاضُ بِرُؤَاك',
    poeticVerseTranslation: 'Bila Simak terbit memancar, air tercurah membanjiri parit, dan kolam penampungan air penuh meluap.',
  },
  {
    number: 15,
    arabicName: 'الغَفْر',
    transliteration: 'Al-Ghafr',
    starGroup: 'ι, κ, λ Virginis',
    zodiacSpan: '0°00\' - 12°51\' Libra (Al-Mīzān)',
    startDegree: 180.0,
    endDegree: 192.8571,
    seasonKey: 'autumn',
    seasonName: 'Musim Gugur (Al-Kharīf)',
    seasonArabic: 'الخَرِيف',
    element: 'Hawa',
    elementLabel: 'Udara (Ḥārr Raṭb)',
    rainfallProbability: 65,
    rainfallVolumeMm: 55,
    rainfallClassification: 'Wasmi',
    rainfallLabel: 'Hujan Wasmi Menyuburkan',
    rainfallArabic: 'وَسْمِيٌّ نَافِعٌ مُبَارَك',
    temperatureIndex: 58,
    temperatureLabel: 'Sejuk Berembun',
    temperatureArabic: 'بَارِدُ اللَّيْلِ كَثِيرُ النَّدَى',
    windDirection: 'Barat (ad-Dabur)',
    windArabic: 'دَبُورٌ رَطْبَة',
    windCharacteristics: 'Embun pagi tebal menutupi ladang bagaikan selimut perak.',
    isMoistureGate: true,
    gateDescription: 'Gerbang equinox musim gugur (*Al-I‘tidāl al-Kharīfī*); keseimbangan siang dan malam.',
    agriculturalIndication: 'Pemanenan buah delima, anggur, dan zaitun perasan pertama (*Az-Zayt al-Bikr*).',
    nauticalIndication: 'Kondisi laut bersahabat dengan angin barat yang teratur.',
    poeticVerse: 'إِذَا طَلَعَ الغَفْر تَسَاوَى اللَّيْلُ مَعَ الفَجْر، وَحَسُنَ فِي الأَعْيُنِ الشَّجَر',
    poeticVerseTranslation: 'Kala Ghafr terbit, malam dan siang berimbang sepadan, dan pepohonan tampak elok berseri.',
  },
  {
    number: 16,
    arabicName: 'الزُّبَانَى',
    transliteration: 'Az-Zubana',
    starGroup: 'α & β Librae (Capit Timbangan)',
    zodiacSpan: '12°51\' - 25°43\' Libra (Al-Mīzān)',
    startDegree: 192.8571,
    endDegree: 205.7143,
    seasonKey: 'autumn',
    seasonName: 'Musim Gugur (Al-Kharīf)',
    seasonArabic: 'الخَرِيف',
    element: 'Hawa',
    elementLabel: 'Udara (Ḥārr Raṭb)',
    rainfallProbability: 70,
    rainfallVolumeMm: 60,
    rainfallClassification: 'Wasmi',
    rainfallLabel: 'Hujan Deras Disertai Angin Basah',
    rainfallArabic: 'أَمْطَارٌ رَطْبَةٌ غَزِيرَة',
    temperatureIndex: 52,
    temperatureLabel: 'Mulai Dingin Menusuk',
    temperatureArabic: 'بُرُودَةٌ مَلْحُوظَةٌ بِاللَّيْل',
    windDirection: 'Barat (ad-Dabur)',
    windArabic: 'غَرْبِيَّةٌ بَحْرِيَّةٌ مُحَمَّلَةٌ بِالمَطَر',
    windCharacteristics: 'Tiupan angin maritim kuat yang membawa uap air dari samudra.',
    isMoistureGate: true,
    gateDescription: 'Pintu air musim gugur terbuka lebar; kelembaban udara meningkat drastis.',
    agriculturalIndication: 'Penanaman bibit pohon baru agar akar kokoh menyerap air hujan wasmi.',
    nauticalIndication: 'Waspada hempasan ombak barat di pelabuhan terbuka.',
    poeticVerse: 'إِذَا طَلَعَتِ الزُّبَانَى كَثُرَتِ السَّوَانِي، وَتَهَادَتِ الأَمَانِي، وَنَالَ الفَلَّاحُ مَا عَانَى',
    poeticVerseTranslation: 'Bila Zubana terbit, kincir air berputar giat, harapan terwujud dan petani menuai manisnya jerih payah.',
  },
  {
    number: 17,
    arabicName: 'الإِكْلِيل',
    transliteration: 'Al-Iklil',
    starGroup: 'β, δ, π Scorpii (Mahkota Scorpio)',
    zodiacSpan: '25°43\' Libra - 8°34\' Scorpio (Al-‘Aqrab)',
    startDegree: 205.7143,
    endDegree: 218.5714,
    seasonKey: 'autumn',
    seasonName: 'Musim Gugur (Al-Kharīf)',
    seasonArabic: 'الخَرِيف',
    element: 'Ma',
    elementLabel: 'Air (Bārid Raṭb)',
    rainfallProbability: 82,
    rainfallVolumeMm: 75,
    rainfallClassification: 'Ghazir',
    rainfallLabel: 'Hujan Lebat Musim Gugur (Wasmiyyah)',
    rainfallArabic: 'وَسْمِيٌّ شَدِيدُ الهُطُول',
    temperatureIndex: 45,
    temperatureLabel: 'Dingin Lembab Menusuk',
    temperatureArabic: 'بَارِدٌ رَطْبٌ شَدِيدُ الوَقْع',
    windDirection: 'Utara (ash-Shamal)',
    windArabic: 'شَمَالِيَّةٌ قَارِسَة',
    windCharacteristics: 'Angin utara bercampur hujan lebat; kabut pegunungan turun tebal.',
    isMoistureGate: true,
    gateDescription: 'Gerbang hujan emas musim gugur. Airnya sangat ditunggu untuk sumur dan telaga.',
    agriculturalIndication: 'Waktu utama membajak tanah berbatu dan menyemai benih tanaman tahan dingin.',
    nauticalIndication: 'Laut mulai bergelora tinggi; kapal kecil disarankan merapat ke pelabuhan.',
    poeticVerse: 'إِذَا طَلَعَ الإِكْلِيل خَرَّتِ السُّيُولُ فِي المَسِيل، وَأَمْسَى البَرْدُ ثَقِيل',
    poeticVerseTranslation: 'Kala Iklil terbit memahkotai langit, banjir mengalir deras di palung sungai, dan hawa dingin kian mencengkeram.',
  },
  {
    number: 18,
    arabicName: 'القَلْب',
    transliteration: 'Al-Qalb',
    starGroup: 'α Scorpii (Antares / Qalb al-‘Aqrab)',
    zodiacSpan: '8°34\' - 21°26\' Scorpio (Al-‘Aqrab)',
    startDegree: 218.5714,
    endDegree: 231.4286,
    seasonKey: 'autumn',
    seasonName: 'Musim Gugur (Al-Kharīf)',
    seasonArabic: 'الخَرِيف',
    element: 'Nar',
    elementLabel: 'Api (Ḥārr Yābis)',
    rainfallProbability: 58,
    rainfallVolumeMm: 45,
    rainfallClassification: 'Wasmi',
    rainfallLabel: 'Petir & Kilat Bersahutan (Barq & Ra‘d)',
    rainfallArabic: 'عَوَاصِفُ رَعْدِيَّةٌ بَرْقِيَّة',
    temperatureIndex: 40,
    temperatureLabel: 'Dingin Berangin Ribut',
    temperatureArabic: 'بُرُودَةٌ شَدِيدَةٌ مَعَ رِيَاح',
    windDirection: 'Selatan (al-Janub)',
    windArabic: 'جَنُوبٌ عَاصِفَة',
    windCharacteristics: 'Awan petir gelap gulita dengan kilat merah membakar langit senja.',
    isMoistureGate: false,
    gateDescription: 'Pertarungan elemen api (Antares merah) dengan dinginnya musim hujan.',
    agriculturalIndication: 'Pengikatan dahan pohon agar tidak patah tertiup badai kilat.',
    nauticalIndication: 'Bahaya badai squall mendadak di laut lepas; hindari pelayaran malam hari.',
    poeticVerse: 'إِذَا طَلَعَ القَلْب جَاءَ الشِّتَاءُ كَالذِّئْب، وَأَلْحَفَ الرَّجُلَ فِي الثَّوْب',
    poeticVerseTranslation: 'Bila Qalb terbit, musim dingin menerkam laksana serigala, dan manusia merapatkan selimut jubah tebal.',
  },
  {
    number: 19,
    arabicName: 'الشَّوْلَة',
    transliteration: 'Ash-Shawlah',
    starGroup: 'λ & υ Scorpii (Sengat Kalajengking)',
    zodiacSpan: '21°26\' Scorpio - 4°17\' Sagittarius (Al-Qaws)',
    startDegree: 231.4286,
    endDegree: 244.2857,
    seasonKey: 'autumn',
    seasonName: 'Musim Gugur (Al-Kharīf)',
    seasonArabic: 'الخَرِيف',
    element: 'Ma',
    elementLabel: 'Air (Bārid Raṭb)',
    rainfallProbability: 78,
    rainfallVolumeMm: 70,
    rainfallClassification: 'Ghazir',
    rainfallLabel: 'Hujan Dingin Lebat Terus Menerus',
    rainfallArabic: 'مَطَرٌ شَتَوِيٌّ دِيمَةٌ مُتَوَاصِلَة',
    temperatureIndex: 35,
    temperatureLabel: 'Sangat Dingin Menusuk Tulang',
    temperatureArabic: 'بَرْدٌ شَدِيدٌ يُقَطِّعُ الأَنْفَاس',
    windDirection: 'Utara (ash-Shamal)',
    windArabic: 'شَمَالٌ صَرْصَرٌ قَارِسَة',
    windCharacteristics: 'Hembusan angin utara yang mematangkan embun beku (*Jalīd*) di atas dedaunan.',
    isMoistureGate: true,
    gateDescription: 'Gerbang transisi menuju dingin ekstrem musim dingin.',
    agriculturalIndication: 'Penutupan tanaman muda dengan jerami pelindung dari embun beku.',
    nauticalIndication: 'Laut berombak ganas; musim badai musim dingin dimulai.',
    poeticVerse: 'إِذَا طَلَعَتِ الشَّوْلَة عَظُمَتِ الصَّوْلَة، وَاشْتَدَّتِ الجَوْلَة، وَبَرَدَتِ العَوْلَة',
    poeticVerseTranslation: 'Kala Shawlah terbit, dahsyatlah serbuan dingin, angin kencang berputar dan tungku perapian dicari.',
  },
  {
    number: 20,
    arabicName: 'النَّعَائِم',
    transliteration: 'An-Na‘a’im',
    starGroup: 'γ, δ, ε, η, ζ, σ, τ, φ Sagittarii',
    zodiacSpan: '4°17\' - 17°09\' Sagittarius (Al-Qaws)',
    startDegree: 244.2857,
    endDegree: 257.1429,
    seasonKey: 'autumn',
    seasonName: 'Musim Gugur (Al-Kharīf)',
    seasonArabic: 'الخَرِيف',
    element: 'Nar',
    elementLabel: 'Api (Ḥārr Yābis)',
    rainfallProbability: 60,
    rainfallVolumeMm: 48,
    rainfallClassification: 'Wasmi',
    rainfallLabel: 'Hujan Salju Pegunungan / Gerimis Beku',
    rainfallArabic: 'أَمْطَارٌ ثَلْجِيَّةٌ فِي المُرْتَفَعَات',
    temperatureIndex: 28,
    temperatureLabel: 'Dingin Ekstrem Pegunungan',
    temperatureArabic: 'بُرُودَةٌ قَارِسَةٌ مُتَجَمِّدَة',
    windDirection: 'Timur (as-Saba)',
    windArabic: 'صَبَا بَارِدَةٌ جِدًّا',
    windCharacteristics: 'Angin timur kering yang membawa kristal es halus dari dataran tinggi.',
    isMoistureGate: true,
    gateDescription: 'Gerbang pembekuan air di bejana terbuka saat malam hari.',
    agriculturalIndication: 'Masa istirahat tanah vegetasi (*Hibernasi Tanah*); perbaikan alat-alat pertanian.',
    nauticalIndication: 'Pelayaran antar benua ditunda menunggu cuaca stabil.',
    poeticVerse: 'إِذَا طَلَعَتِ النَّعَائِم تَبَرَّدَتِ البَهَائِم، وَتَقَاعَسَتِ العَزَائِم، وَلَزِمَ المَنَازِلَ النَّائِم',
    poeticVerseTranslation: 'Bila Na‘a’im terbit, hewan ternak menggigil kedinginan, langkah melemah dan manusia meringkuk di rumah.',
  },
  {
    number: 21,
    arabicName: 'البَلْدَة',
    transliteration: 'Al-Baldah',
    starGroup: 'Ruang kosong tanpa bintang terang di Sagittarius',
    zodiacSpan: '17°09\' Sagittarius - 0°00\' Capricorn (Al-Jady)',
    startDegree: 257.1429,
    endDegree: 270.0,
    seasonKey: 'autumn',
    seasonName: 'Musim Gugur (Al-Kharīf)',
    seasonArabic: 'الخَرِيف',
    element: 'Turab',
    elementLabel: 'Tanah (Bārid Yābis)',
    rainfallProbability: 30,
    rainfallVolumeMm: 20,
    rainfallClassification: 'Tal',
    rainfallLabel: 'Langit Cerah Bersih Berembun Beku (Jalid)',
    rainfallArabic: 'صَفَاءٌ قَارِسٌ مَعَ جَلِيد',
    temperatureIndex: 20,
    temperatureLabel: 'Malam Terdingin dalam Setahun',
    temperatureArabic: 'أَبْرَدُ لَيَالِي العَام (صَقِيع)',
    windDirection: 'Utara (ash-Shamal)',
    windArabic: 'شَمَالٌ صَقِيعِيَّة',
    windCharacteristics: 'Langit biru pekat tanpa awan; radiasi panas bumi terlepas bebas ke angkasa.',
    isMoistureGate: false,
    gateDescription: 'Dikenal sebagai "tanah sunyi"; udara sangat kering dan membeku tanpa curah hujan berarti.',
    agriculturalIndication: 'Perlindungan pohon kurma dan tanaman zaitun dari bahaya pembekuan batang (*As-Saqī‘*).',
    nauticalIndication: 'Laut tampak tenang membeku, namun bahaya hipotermia bagi pelaut tinggi.',
    poeticVerse: 'إِذَا طَلَعَتِ البَلْدَة حَمِدَتِ النَّارُ فِي القِدْرَة، وَكَمِدَتِ الوَجَنَاتُ مِنَ البَرْدَة',
    poeticVerseTranslation: 'Kala Baldah tampak, api di perapian disyukuri, dan pipi memerah membeku digigit dinginnya angin.',
  },
  {
    number: 22,
    arabicName: 'سَعْدُ الذَّابِح',
    transliteration: 'Sa‘d adh-Dhabih',
    starGroup: 'α & β Capricorni',
    zodiacSpan: '0°00\' - 12°51\' Capricorn (Al-Jady)',
    startDegree: 270.0,
    endDegree: 282.8571,
    seasonKey: 'winter',
    seasonName: 'Musim Dingin (Ash-Shitā’)',
    seasonArabic: 'الشِّتَاء',
    element: 'Turab',
    elementLabel: 'Tanah (Bārid Yābis)',
    rainfallProbability: 55,
    rainfallVolumeMm: 45,
    rainfallClassification: 'Ghayth',
    rainfallLabel: 'Hujan Dingin Disertai Butiran Es',
    rainfallArabic: 'مَطَرٌ قَارِسٌ وَبَرَد',
    temperatureIndex: 18,
    temperatureLabel: 'Puncak Dingin Solstis Musim Dingin',
    temperatureArabic: 'ذِرْوَةُ شِتَاءِ الكَنُوس',
    windDirection: 'Barat (ad-Dabur)',
    windArabic: 'دَبُورٌ شَتَوِيَّةٌ عَنِيفَة',
    windCharacteristics: 'Hembusan angin barat laut kencang membawa hujan es dan kabut es tebal.',
    isMoistureGate: true,
    gateDescription: 'Gerbang solstis musim dingin (*Al-Inqilāb ash-Shatwī*); malam terpanjang dalam setahun.',
    agriculturalIndication: 'Pemangkasan pohon anggur dan pohon buah yang sedang meranggas daunnya.',
    nauticalIndication: 'Laut badai musim dingin; kapal dagang besar berlabuh aman di teluk terlindung.',
    poeticVerse: 'إِذَا طَلَعَ سَعْدُ الذَّابِح ذَبَحَ البَرْدُ الصَّاحِب، وَلَمْ يُنْبِحْ كَلْبٌ لِنَابِح',
    poeticVerseTranslation: 'Bila Sa‘d Dhabih terbit, dingin menusuk menyembelih raga musafir, hingga anjing pun enggan menggonggong.',
  },
  {
    number: 23,
    arabicName: 'سَعْدُ بُلَع',
    transliteration: 'Sa‘d Bula‘',
    starGroup: 'μ & ε Aquarii',
    zodiacSpan: '12°51\' - 25°43\' Capricorn (Al-Jady)',
    startDegree: 282.8571,
    endDegree: 295.7143,
    seasonKey: 'winter',
    seasonName: 'Musim Dingin (Ash-Shitā’)',
    seasonArabic: 'الشِّتَاء',
    element: 'Hawa',
    elementLabel: 'Udara (Ḥārr Raṭb)',
    rainfallProbability: 85,
    rainfallVolumeMm: 80,
    rainfallClassification: 'Ghazir',
    rainfallLabel: 'Bumi Menelan Air Hujan Melimpah (Bula‘)',
    rainfallArabic: 'غَيْثٌ سَكُوبٌ تَبْتَلِعُهُ الأَرْض',
    temperatureIndex: 25,
    temperatureLabel: 'Dingin Basah Lembab',
    temperatureArabic: 'بَارِدٌ مَاطِرٌ رَطْب',
    windDirection: 'Barat (ad-Dabur)',
    windArabic: 'غَرْبِيَّةٌ دَافِقَةٌ بِالمِيَاه',
    windCharacteristics: 'Hujan deras berkesinambungan; bumi menyerap air hujan laksana menelannya dengan cepat.',
    isMoistureGate: true,
    gateDescription: 'Gerbang kelimpahan air bawah tanah! Dinamakan "Bula‘" karena bumi menelan air hujan dengan cepat.',
    agriculturalIndication: 'Penampungan air hujan ke waduk dan kolam retensi (*Al-Hawāmil*).',
    nauticalIndication: 'Waspada luapan banjir bandang di muara sungai pesisir.',
    poeticVerse: 'إِذَا طَلَعَ سَعْدُ بُلَع مَلَأَ المَاءُ كُلَّ تَلَع، وَانْفَجَرَتِ العُيُونُ فِي البِقَاع',
    poeticVerseTranslation: 'Kala Sa‘d Bula‘ terbit memancar, air memenuhi parit dan lembah, dan mata air memancar dari perut bumi.',
  },
  {
    number: 24,
    arabicName: 'سَعْدُ السُّعُود',
    transliteration: 'Sa‘d as-Su‘ud',
    starGroup: 'β & ξ Aquarii',
    zodiacSpan: '25°43\' Capricorn - 8°34\' Aquarius (Ad-Dalw)',
    startDegree: 295.7143,
    endDegree: 308.5714,
    seasonKey: 'winter',
    seasonName: 'Musim Dingin (Ash-Shitā’)',
    seasonArabic: 'الشِّتَاء',
    element: 'Hawa',
    elementLabel: 'Udara (Ḥārr Raṭb)',
    rainfallProbability: 75,
    rainfallVolumeMm: 68,
    rainfallClassification: 'Ghayth',
    rainfallLabel: 'Pencairan Air & Keberuntungan Segala Makhluk',
    rainfallArabic: 'جَرَيَانُ المَاءِ فِي العُودِ وَنَمَاء',
    temperatureIndex: 35,
    temperatureLabel: 'Dingin Mulai Menghangat',
    temperatureArabic: 'انْكِسَارُ شِدَّةِ البَرْد',
    windDirection: 'Timur (as-Saba)',
    windArabic: 'صَبَا بَاعِثَةٌ لِلحَيَاة',
    windCharacteristics: 'Getah pohon mulai mengalir kembali di dahan; hawa sejuk bersahabat.',
    isMoistureGate: true,
    gateDescription: 'Bintang segala keberuntungan! Pencairan salju dan hidupnya kembali denyut vegetasi bumi.',
    agriculturalIndication: 'Penyetekan tanaman dan penanaman tunas pohon buah-buahan.',
    nauticalIndication: 'Kondisi pelayaran membaik signifikan; cuaca berangsur stabil.',
    poeticVerse: 'إِذَا طَلَعَ سَعْدُ السُّعُود جَرَى المَاءُ فِي كُلِّ عُود، وَاخْضَرَّتِ الرُّبَى وَالوُهُود',
    poeticVerseTranslation: 'Bila Sa‘d as-Su‘ud terbit, air mengalir di setiap urat kayu, bukit dan jurang menghijau berseri.',
  },
  {
    number: 25,
    arabicName: 'سَعْدُ الأَخْبِيَة',
    transliteration: 'Sa‘d al-Akhbiyah',
    starGroup: 'γ, π, ζ, η Aquarii (Tenda Bintang Tiga)',
    zodiacSpan: '8°34\' - 21°26\' Aquarius (Ad-Dalw)',
    startDegree: 308.5714,
    endDegree: 321.4286,
    seasonKey: 'winter',
    seasonName: 'Musim Dingin (Ash-Shitā’)',
    seasonArabic: 'الشِّتَاء',
    element: 'Hawa',
    elementLabel: 'Udara (Ḥārr Raṭb)',
    rainfallProbability: 62,
    rainfallVolumeMm: 52,
    rainfallClassification: 'Wasmi',
    rainfallLabel: 'Hujan Hangat Penumbuh Tunas',
    rainfallArabic: 'دِفْءٌ مَاطِرٌ يُخْرِجُ الخَبَايَا',
    temperatureIndex: 42,
    temperatureLabel: 'Hangat Sejuk Bermekaran',
    temperatureArabic: 'اعْتِدَالٌ شَتَوِيٌّ مُبَشِّر',
    windDirection: 'Selatan (al-Janub)',
    windArabic: 'جَنُوبٌ دَافِئَةٌ رَطْبَة',
    windCharacteristics: 'Hewan melata dan serangga tanah mulai keluar dari persembunyian bawah tanah (*Al-Akhbiyah*).',
    isMoistureGate: true,
    gateDescription: 'Dinamakan "Akhbiyah" karena segala yang tersembunyi di dalam tanah mulai menampakkan diri.',
    agriculturalIndication: 'Penyemaian bibit tanaman palawija dan sayuran awal.',
    nauticalIndication: 'Angin selatan hangat memudahkan perjalanan kapal ke arah utara.',
    poeticVerse: 'إِذَا طَلَعَ سَعْدُ الأَخْبِيَة خَرَجَتْ كُلُّ دَابَّةٍ مُخْبِيَة، وَتَهَيَّأَتِ الأَرْضُ لِلأَغْذِيَة',
    poeticVerseTranslation: 'Bila Sa‘d al-Akhbiyah tampak, keluarlah binatang yang bersembunyi, dan bumi bersiap melimpahkan pangan.',
  },
  {
    number: 26,
    arabicName: 'الفَرْغُ المُقَدَّم',
    transliteration: 'Al-Fargh al-Muqaddam',
    starGroup: 'α & β Pegasi (Mulut Ember Air)',
    zodiacSpan: '21°26\' Aquarius - 4°17\' Pisces (Al-Ḥūt)',
    startDegree: 321.4286,
    endDegree: 334.2857,
    seasonKey: 'winter',
    seasonName: 'Musim Dingin (Ash-Shitā’)',
    seasonArabic: 'الشِّتَاء',
    element: 'Ma',
    elementLabel: 'Air (Bārid Raṭb)',
    rainfallProbability: 92,
    rainfallVolumeMm: 95,
    rainfallClassification: 'Ghazir',
    rainfallLabel: 'Curahan Ember Air Langit (Al-Fargh)',
    rainfallArabic: 'أَعْظَمُ سَكْبٍ لِلمِيَاهِ مِنَ السَّمَاء',
    temperatureIndex: 44,
    temperatureLabel: 'Sejuk Basah Kuyup',
    temperatureArabic: 'بَارِدٌ رَطْبٌ غَزِيرُ السُّيُول',
    windDirection: 'Barat (ad-Dabur)',
    windArabic: 'دَبُورٌ عَاصِفَةٌ مَاطِرَة',
    windCharacteristics: 'Curah hujan deras melimpah ruah laksana ember air langit yang ditumpahkan.',
    isMoistureGate: true,
    gateDescription: 'Pintu gerbang ember air langit (*Al-Fargh*); volume presipitasi tertinggi dalam siklus anwa\'.',
    agriculturalIndication: 'Waspada luapan banjir di dataran rendah; pengalihan air ke parit pembuangan.',
    nauticalIndication: 'Bahaya gelombang tinggi di laut samudra terbuka; prioritaskan pelayaran teluk.',
    poeticVerse: 'إِذَا طَلَعَ الفَرْغُ المُقَدَّم انْسَكَبَ المَاءُ المُنْسَجِم، وَرَوِيَتِ الرِّعَاعُ وَالنَّعَم',
    poeticVerseTranslation: 'Kala Fargh Muqaddam terbit, tertumpahlah air hujan lebat membahana, memuaskan dahaga ternak dan manusia.',
  },
  {
    number: 27,
    arabicName: 'الفَرْغُ المُؤَخَّر',
    transliteration: 'Al-Fargh al-Mu’akhkhar',
    starGroup: 'γ Pegasi & α Andromedae (Belakang Ember Air)',
    zodiacSpan: '4°17\' - 17°09\' Pisces (Al-Ḥūt)',
    startDegree: 334.2857,
    endDegree: 347.1429,
    seasonKey: 'winter',
    seasonName: 'Musim Dingin (Ash-Shitā’)',
    seasonArabic: 'الشِّتَاء',
    element: 'Ma',
    elementLabel: 'Air (Bārid Raṭb)',
    rainfallProbability: 86,
    rainfallVolumeMm: 85,
    rainfallClassification: 'Ghazir',
    rainfallLabel: 'Kelanjutan Aliran Air Melimpah',
    rainfallArabic: 'سَحَّاحٌ مُتَتَابِعٌ رَطْب',
    temperatureIndex: 46,
    temperatureLabel: 'Sejuk Bersih Menghangat',
    temperatureArabic: 'رَطْبٌ لَطِيفُ البُرُودَة',
    windDirection: 'Timur (as-Saba)',
    windArabic: 'صَبَا نَدِيَّة',
    windCharacteristics: 'Hujan reda perlahan menyisakan sungai yang mengalir deras dan danau penuh.',
    isMoistureGate: true,
    gateDescription: 'Sisi penutup dari ember air langit; penyempurnaan pengisian cadangan air bumi.',
    agriculturalIndication: 'Tanah mencapai kapasitas kelembaban maksimum (*Kapasitas Lapang*); sangat subur untuk tanaman.',
    nauticalIndication: 'Ombak laut mulai tenang kembali; angin bertiup konsisten.',
    poeticVerse: 'إِذَا طَلَعَ الفَرْغُ الأَخِير اخْضَرَّتِ القِفَارُ بِالنَّضِير، وَاسْتَبْشَرَ الصَّغِيرُ وَالكَبِير',
    poeticVerseTranslation: 'Bila Fargh Akhir terbit, padang gersang menghijau permai, dan bersuka citalah segenap tua dan muda.',
  },
  {
    number: 28,
    arabicName: 'بَطْنُ الحُوت / الرِّشَاء',
    transliteration: 'Batn al-Hut / Ar-Risha',
    starGroup: 'β Andromedae (Mirach / Tali Ember Ikan)',
    zodiacSpan: '17°09\' Pisces - 0°00\' Aries (Al-Ḥamal)',
    startDegree: 347.1429,
    endDegree: 360.0,
    seasonKey: 'winter',
    seasonName: 'Musim Dingin (Ash-Shitā’)',
    seasonArabic: 'الشِّتَاء',
    element: 'Ma',
    elementLabel: 'Air (Bārid Raṭb)',
    rainfallProbability: 68,
    rainfallVolumeMm: 58,
    rainfallClassification: 'Wasmi',
    rainfallLabel: 'Hujan Penutup Siklus & Penyambut Musim Semi',
    rainfallArabic: 'خِتَامُ الأَنْوَاءِ الشَّتَوِيَّةِ وَبَدْءُ الإِزْهَار',
    temperatureIndex: 50,
    temperatureLabel: 'Sejuk Menjelang Semi',
    temperatureArabic: 'مُعْتَدِلٌ يَفُوحُ بِعِطْرِ الإِزْهَار',
    windDirection: 'Utara (ash-Shamal)',
    windArabic: 'شَمَالٌ لَطِيفَةٌ نَقِيَّة',
    windCharacteristics: 'Hujan gerimis segar yang memicu mekarnya kuncup bunga pertama di pepohonan.',
    isMoistureGate: true,
    gateDescription: 'Titik penutup dari 28 Manzil Falak, menyambung kembali ke gerbang pertama (Ash-Sharatan).',
    agriculturalIndication: 'Pemupukan susulan dan perawatan bunga buah agar tidak rontok.',
    nauticalIndication: 'Musim berlayar musim semi resmi dibuka di seluruh pelabuhan dunia Islam.',
    poeticVerse: 'إِذَا طَلَعَ الرِّشَاء كَثُرَ فِي الأَرْضِ النَّمَاء، وَانْتَهَتْ شِدَّةُ الشِّتَاء، وَعَادَ الرَّبِيعُ بِالبَهَاء',
    poeticVerseTranslation: 'Bila Ar-Risha terbit di ufuk fajar, berlimpahlah kesuburan bumi, tuntas sudah kepedihan dingin dan musim semi kembali bermahkota keagungan.',
  },
];

/**
 * Get the Lunar Mansion profile based on Moon's ecliptic longitude (0-360°)
 */
export function getManzilWeatherFromMoonLongitude(moonLongitudeDeg: number): {
  manzil: ManzilWeatherProfile;
  degreeInMansion: number;
  percentageInMansion: number;
} {
  const normDeg = ((moonLongitudeDeg % 360) + 360) % 360;
  const mansionSpan = 360 / 28; // 12.857142857°
  const index = Math.min(27, Math.floor(normDeg / mansionSpan));
  const manzil = MANZIL_WEATHER_PROFILES[index];
  const degreeInMansion = normDeg - manzil.startDegree;
  const percentageInMansion = (degreeInMansion / mansionSpan) * 100;

  return {
    manzil,
    degreeInMansion,
    percentageInMansion,
  };
}

/**
 * Correlate Moon's active Manzil with active season's forecast
 */
export function correlateMoonManzilWithSeason(
  moonMansion: ManzilWeatherProfile,
  seasonKey: 'spring' | 'summer' | 'autumn' | 'winter',
  seasonalRainBase: number
): {
  correlationType: 'amplified_rain' | 'suppressed_rain' | 'harmonious_moisture' | 'dry_heat_peak' | 'frost_alert';
  correlationTitle: string;
  correlationArabic: string;
  combinedRainfallIndex: number;
  effectDescription: string;
  recommendation: string;
} {
  const combinedRain = Math.round((seasonalRainBase * 0.45) + (moonMansion.rainfallProbability * 0.55));

  if (moonMansion.isMoistureGate && moonMansion.rainfallProbability >= 70) {
    return {
      correlationType: 'amplified_rain',
      correlationTitle: 'Penguatan Curah Hujan Signifikan (Pintu Air Terbuka)',
      correlationArabic: 'فَتْحُ أَبْوَابِ السَّمَاءِ بِالمَاءِ المُنْهَمِر',
      combinedRainfallIndex: Math.min(100, combinedRain + 10),
      effectDescription: `Posisi Bulan di Manzil #${moonMansion.number} (${moonMansion.transliteration}) membuka pintu kelembaban langit (*Fatḥ al-Bāb*). Kombinasi dengan musim ${seasonKey} melipatgandakan potensi hujan deras (*Naw' Ghazir*) dan angin basah ${moonMansion.windDirection}.`,
      recommendation: 'Siapkan saluran drainase pertanian, tampung cadangan air tawar, dan waspadai potensi genangan di dataran rendah.',
    };
  }

  if (moonMansion.rainfallProbability <= 20) {
    return {
      correlationType: 'suppressed_rain',
      correlationTitle: 'Penekanan Curah Hujan & Gelombang Kering',
      correlationArabic: 'قَحْطٌ وَانْحِبَاسٌ لِلأَمْطَار',
      combinedRainfallIndex: Math.max(5, combinedRain - 10),
      effectDescription: `Posisi Bulan di Manzil #${moonMansion.number} (${moonMansion.transliteration}) yang berunsur ${moonMansion.elementLabel} menekan pembentukan awan hujan. Udara cenderung kering panas dengan hembusan angin ${moonMansion.windDirection}.`,
      recommendation: 'Lakukan irigasi terkontrol di waktu petang atau fajar untuk meminimalkan laju penguapan (*Evapotranspirasi*).',
    };
  }

  if (moonMansion.temperatureIndex <= 25) {
    return {
      correlationType: 'frost_alert',
      correlationTitle: 'Peringatan Embun Beku & Hawa Dingin Ekstrem',
      correlationArabic: 'تَحْذِيرٌ مِنَ الجَلِيدِ وَالصَّقِيع',
      combinedRainfallIndex: combinedRain,
      effectDescription: `Bulan berada di stasiun dingin ekstrem #${moonMansion.number} (${moonMansion.transliteration}). Radiasi panas malam hari terlepas cepat memicu embun beku (*Jalīd*) di atas dedaunan.`,
      recommendation: 'Lindungi tanaman sensitif dingin dengan jerami pelindung atau rumah kaca tradisional.',
    };
  }

  return {
    correlationType: 'harmonious_moisture',
    correlationTitle: 'Keseimbangan Kelembaban & Udara Bersahabat',
    correlationArabic: 'اعْتِدَالُ الأَنْوَاءِ وَطِيبُ الهَوَاء',
    combinedRainfallIndex: combinedRain,
    effectDescription: `Posisi Bulan di Manzil #${moonMansion.number} (${moonMansion.transliteration}) bersinergi selaras dengan musim ${seasonKey}. Menghasilkan curah hujan terukur, angin sepoi bersahabat, dan suhu yang kondusif.`,
    recommendation: 'Kondisi ideal untuk seluruh aktivitas agrikultur, penyerbukan bunga, dan perjalanan darat maupun laut.',
  };
}
